version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - proxy
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./env/db.env
    restart: always

  redis:
    image: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  app:
    image: crazymax/nextcloud
    domainname: example.com
    hostname: nextcloud
    depends_on:
      - letsencrypt
      - proxy
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - ./ssmtp:/etc/ssmtp
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=db
    env_file:
      - ./env/db.env
      - ./env/proxy.env
      - ./env/ssmtp.env
    restart: always

volumes:
  nextcloud:
